//NESTED TRY CATCH BLOCK

class DemoExce3 {
	public static void main(String[] args) {
		try
		{
			int x = 10/0;
			System.out.println(x);
		}
		catch(ArithmeticException ae) {
			
		}
		

	}

}
